### ISSUE TITLE
the crops Ore Dictionary is bug

### ISSUE THREAD

**Issue by jiuyaolx** [BedrockLegends/Monumental-Experience#27]
**Please do not posted issues that are asking for Server Files**

**Issue description:**
Pick up the vanilla carrots, Nether Wart, Blackberries, Raspberries and other items from Simple Farming to become Rice from Simple Farming.
The Ore Dictionary is messy

**Steps to reproduce:**
1.
2.
3.

 
**Version (make sure you are on the latest version before reporting, Do not put latest or last updated):**
8.4
**Forge Version:**
36.0.22

**Server Version:**

**Modpack Version:**
8.4

**Have you customized any settings in the pack prior to posting your issue, Please type Yes or No below.**
no
 
If a  Crash log is relevant for this issue, link it here using one of the sites below.)
Do not post your crash log without using one of the sites below.

 

**Gist:** https://gist.github.com/

**Pastebin:** https://pastebin.com/

**Hastebin:** https://hastebin.com/

**Comment by Deathstar175** [comment]
I found the problem, there was an extra tag in the conversion and should be fixed in a coming update. 
If you go to this file \config\autooredictconv-conversions.cfg and delete the line below, everything should be fine until the next update comes out..
enhancedcelestials:harvest_moon_whitelisted_crop_drops=simplefarming:rice
